name:        'Annotate Ruby & Ember Test Failures'
description: 'Annotate git with test failures'
author:      'Joe Gaudet <joe.gaudet@food.ee>'
runs:
  using: 'node12'
  main:  'index.js'
branding:
  icon:  'search'
  color: 'red'
inputs:
  report-file:
    description: 'Path to the file where the xunit test report file lives'
    required: true
    default: ''
  map-file:
    description: 'The path to a js file map file'
  test-root:
    description: 'The path to a test folder'
  check-name:
    description: 'The name of the check this action is running in'
    required: true
  language:
    description: 'The name of the language the check is running against'
    required: true
